services:
  app:
    build: .
    container_name: api360_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - shared_net # Solo el nombre aquí
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgres:16-alpine
    container_name: api360_db
    restart: always
    environment:
      POSTGRES_DB: api360_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_net # Solo el nombre aquí

# SECCIÓN GLOBAL DE REDES (Aquí es donde se define la configuración)
networks:
  shared_net:
    external: true
    name: 360_shared_network

volumes:
  postgres_data:
